CREATE SCHEMA PAYMENT;

CREATE TABLE PAYMENT.PAYMENT_METHOD(
    ID VARCHAR(30) NOT NULL PRIMARY KEY
);

CREATE TABLE PAYMENT.PAYMENT(
    ID IDENTITY NOT NULL PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    AMOUNT NUMERIC(10, 2),
    PAYMENT_METHOD VARCHAR(30) NOT NULL,
    CREATED TIMESTAMP NOT NULL
);

ALTER TABLE PAYMENT.PAYMENT
ADD FOREIGN KEY (PAYMENT_METHOD)
REFERENCES PAYMENT.PAYMENT_METHOD(ID);

ALTER TABLE PAYMENT.PAYMENT -- Note! cross schema FK
ADD FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER.CUSTOMER(ID);

INSERT INTO PAYMENT.PAYMENT_METHOD (ID) VALUES ('PAYPAL');
INSERT INTO PAYMENT.PAYMENT_METHOD (ID) VALUES ('VISA');
INSERT INTO PAYMENT.PAYMENT_METHOD (ID) VALUES ('MASTERCARD');
INSERT INTO PAYMENT.PAYMENT_METHOD (ID) VALUES ('CASH');
