CREATE SCHEMA CUSTOMER;

CREATE TABLE CUSTOMER.CUSTOMER(
    ID IDENTITY NOT NULL PRIMARY KEY,
    SSN VARCHAR(20) NOT NULL,
    USERNAME VARCHAR(80) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(30) NOT NULL,
    CREATED TIMESTAMP NOT NULL
);

INSERT INTO CUSTOMER.CUSTOMER (SSN, USERNAME, FIRST_NAME, LAST_NAME, PHONE_NUMBER, CREATED)
VALUES ('123451234', 'username1', 'Ben', 'Abraham', '071231341', CURRENT_TIMESTAMP());

INSERT INTO CUSTOMER.CUSTOMER (SSN, USERNAME, FIRST_NAME, LAST_NAME, PHONE_NUMBER, CREATED)
VALUES ('313241345', 'username2', 'Jenny', 'Foster', '072843714', CURRENT_TIMESTAMP());

INSERT INTO CUSTOMER.CUSTOMER (SSN, USERNAME, FIRST_NAME, LAST_NAME, PHONE_NUMBER, CREATED)
VALUES ('213453235', 'username3', 'Julia', 'Willis', '072313452', CURRENT_TIMESTAMP());
